### ISSUE TITLE
design ejection system 3D model CAD(springs)

### ISSUE THREAD

**Issue by bytecod3** [nakujaproject/N4-Recovery#37]

**Comment by FortuneMK** [comment]
[springs.pdf](https://github.com/user-attachments/files/15612845/springs.pdf)

**Comment by bytecod3** [comment]
This design needs improvement to add screw terminals for the PCBs and zip ties to hold the battery.
Also look into adding a circular plate just around the top to hold the XBee module for telemetry transmission.
